// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizzTiengNhat.Models;

#nullable disable

namespace QuizzTiengNhat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329025756_AddChatSupport")]
    partial class AddChatSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamTemplate", b =>
                {
                    b.Property<Guid>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<double>("MinLanguageKnowledgeScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinListeningScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinReadingScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalMaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TemplateID");

                    b.HasIndex("LevelID");

                    b.ToTable("ExamTemplates");
                });

            modelBuilder.Entity("ExamTemplateDetail", b =>
                {
                    b.Property<Guid>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PointPerQuestion")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateID")
                        .HasColumnType("uuid");

                    b.HasKey("DetailID");

                    b.HasIndex("TemplateID");

                    b.ToTable("ExamTemplateDetails");
                });

            modelBuilder.Entity("Exams", b =>
                {
                    b.Property<Guid>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<double>("MinLanguageKnowledgeScore")
                        .HasColumnType("double precision");

                    b.Property<double>("MinListeningScore")
                        .HasColumnType("double precision");

                    b.Property<double>("MinReadingScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ShowResultImmediately")
                        .HasColumnType("boolean");

                    b.Property<int?>("TargetSkill")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalMaxScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.HasIndex("TemplateID");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Answers", b =>
                {
                    b.Property<Guid>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uuid");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LevelID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedAdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminId");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatRoundRobinState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastAssignedIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChatRoundRobinStates");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Courses", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.HasKey("CourseID");

                    b.HasIndex("LevelID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Exam_Questions", b =>
                {
                    b.Property<Guid>("ExamQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamID")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionsQuestionID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExamQuestionID");

                    b.HasIndex("ExamID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("QuestionsQuestionID");

                    b.ToTable("Exam_Questions");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Exam_Results", b =>
                {
                    b.Property<Guid>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamID")
                        .HasColumnType("uuid");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("integer");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResultID");

                    b.HasIndex("ExamID");

                    b.HasIndex("UserID");

                    b.ToTable("Exam_Results");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Examples", b =>
                {
                    b.Property<Guid>("ExampleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioURL")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrammarID")
                        .HasColumnType("uuid");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VocabID")
                        .HasColumnType("uuid");

                    b.HasKey("ExampleID");

                    b.HasIndex("GrammarID");

                    b.HasIndex("VocabID");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.GrammarGroups", b =>
                {
                    b.Property<Guid>("GrammarGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GrammarGroupID");

                    b.ToTable("GrammarGroups");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.GrammarTopics", b =>
                {
                    b.Property<Guid>("GrammarID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("GrammarID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("GrammarTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Grammars", b =>
                {
                    b.Property<Guid>("GrammarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Formality")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrammarGroupID")
                        .HasColumnType("uuid");

                    b.Property<int>("GrammarType")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageNote")
                        .HasColumnType("text");

                    b.HasKey("GrammarID");

                    b.HasIndex("GrammarGroupID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.ToTable("Grammars");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.JLPT_Level", b =>
                {
                    b.Property<Guid>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LevelID");

                    b.ToTable("JLPT_Levels");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Kanjis", b =>
                {
                    b.Property<Guid>("KanjiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kunyomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mnemonics")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Onyomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RadicalID")
                        .HasColumnType("uuid");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeGif")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KanjiID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.HasIndex("RadicalID");

                    b.HasIndex("TopicID");

                    b.ToTable("Kanjis");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Lessons", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid?>("JLPT_LevelLevelID")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseID");

                    b.HasIndex("JLPT_LevelLevelID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Lessons_Topic", b =>
                {
                    b.Property<Guid>("LessonsID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("LessonsID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("Lessons_Topics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ListeningTopics", b =>
                {
                    b.Property<Guid>("ListeningID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("ListeningID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("ListeningTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Listenings", b =>
                {
                    b.Property<Guid>("ListeningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<string>("SpeedCategory")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ListeningID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.ToTable("Listenings");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Progress", b =>
                {
                    b.Property<Guid>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonsID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgressID");

                    b.HasIndex("LessonsID");

                    b.HasIndex("UserID");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Questions", b =>
                {
                    b.Property<Guid>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioURL")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EquivalentID")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .HasColumnType("text");

                    b.Property<Guid?>("JLPT_LevelLevelID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonsLessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ListeningID")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaTimestamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReadingID")
                        .HasColumnType("uuid");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuestionID");

                    b.HasIndex("JLPT_LevelLevelID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LessonsLessonID");

                    b.HasIndex("ListeningID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ReadingID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Questions_Topic", b =>
                {
                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("Questions_Topics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.RadicalVariants", b =>
                {
                    b.Property<Guid>("VariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meaning")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RadicalID")
                        .HasColumnType("uuid");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.HasKey("VariantID");

                    b.HasIndex("RadicalID");

                    b.ToTable("RadicalVariants");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Radicals", b =>
                {
                    b.Property<Guid>("RadicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meaning")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.HasKey("RadicalID");

                    b.ToTable("Radicals");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ReadingTopics", b =>
                {
                    b.Property<Guid>("ReadingID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("ReadingID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("ReadingTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Readings", b =>
                {
                    b.Property<Guid>("ReadingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("ReadingID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Topics", b =>
                {
                    b.Property<Guid>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabTopics", b =>
                {
                    b.Property<Guid>("VocabID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uuid");

                    b.HasKey("VocabID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("VocabTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabWordTypes", b =>
                {
                    b.Property<Guid>("VocabID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordTypeID")
                        .HasColumnType("uuid");

                    b.HasKey("VocabID", "WordTypeID");

                    b.HasIndex("WordTypeID");

                    b.ToTable("VocabWordTypes");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Vocabularies", b =>
                {
                    b.Property<Guid>("VocabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageURL")
                        .HasColumnType("text");

                    b.Property<bool>("IsCommon")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("uuid");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mnemonics")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VocabID");

                    b.HasIndex("LessonID");

                    b.HasIndex("LevelID");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabularyKanjis", b =>
                {
                    b.Property<Guid>("VocabID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KanjiID")
                        .HasColumnType("uuid");

                    b.HasKey("VocabID", "KanjiID");

                    b.HasIndex("KanjiID");

                    b.ToTable("VocabularyKanjis");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.WordTypes", b =>
                {
                    b.Property<Guid>("WordTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WordTypeID");

                    b.ToTable("WordTypes");
                });

            modelBuilder.Entity("ExamTemplate", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany("ExamTemplates")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JLPTLevel");
                });

            modelBuilder.Entity("ExamTemplateDetail", b =>
                {
                    b.HasOne("ExamTemplate", "Template")
                        .WithMany("Details")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Exams", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID");

                    b.HasOne("ExamTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lesson");

                    b.Navigation("Level");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Answers", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Questions", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ApplicationUser", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelID");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatConversation", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", "AssignedAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAdmin");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatMessage", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Courses", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Exam_Questions", b =>
                {
                    b.HasOne("Exams", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Questions", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Questions", null)
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionsQuestionID");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Exam_Results", b =>
                {
                    b.HasOne("Exams", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", "User")
                        .WithMany("ExamResults")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Examples", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Grammars", "Grammar")
                        .WithMany("Examples")
                        .HasForeignKey("GrammarID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizzTiengNhat.Models.Vocabularies", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Grammar");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.GrammarTopics", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Grammars", "Grammar")
                        .WithMany("GrammarTopics")
                        .HasForeignKey("GrammarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("GrammarTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Grammars", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.GrammarGroups", "GrammarGroup")
                        .WithMany("Grammars")
                        .HasForeignKey("GrammarGroupID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany("Grammars")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarGroup");

                    b.Navigation("JLPTLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Kanjis", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany("Kanjis")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Radicals", "Radical")
                        .WithMany("Kanjis")
                        .HasForeignKey("RadicalID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JLPTLevel");

                    b.Navigation("Lesson");

                    b.Navigation("Radical");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Lessons", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Courses", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", null)
                        .WithMany("Lessons")
                        .HasForeignKey("JLPT_LevelLevelID");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Lessons_Topic", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany("LessonTopics")
                        .HasForeignKey("LessonsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("LessonTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ListeningTopics", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Listenings", "Listening")
                        .WithMany("ListeningTopics")
                        .HasForeignKey("ListeningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("ListeningTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listening");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Listenings", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JLPTLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Progress", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.ApplicationUser", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Questions", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", null)
                        .WithMany("Questions")
                        .HasForeignKey("JLPT_LevelLevelID");

                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Lessons", null)
                        .WithMany("Questions")
                        .HasForeignKey("LessonsLessonID");

                    b.HasOne("QuizzTiengNhat.Models.Listenings", "Listening")
                        .WithMany("Questions")
                        .HasForeignKey("ListeningID");

                    b.HasOne("QuizzTiengNhat.Models.Questions", "ParentQuestion")
                        .WithMany("SubQuestions")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizzTiengNhat.Models.Readings", "Reading")
                        .WithMany("Questions")
                        .HasForeignKey("ReadingID");

                    b.Navigation("Lesson");

                    b.Navigation("Listening");

                    b.Navigation("ParentQuestion");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Questions_Topic", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Questions", "Question")
                        .WithMany("QuestionTopics")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("QuestionTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.RadicalVariants", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Radicals", "Radical")
                        .WithMany("RadicalVariants")
                        .HasForeignKey("RadicalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radical");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ReadingTopics", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Readings", "Reading")
                        .WithMany("ReadingTopics")
                        .HasForeignKey("ReadingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("ReadingTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Readings", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JLPTLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabTopics", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Topics", "Topic")
                        .WithMany("VocabTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Vocabularies", "Vocabulary")
                        .WithMany("VocabTopics")
                        .HasForeignKey("VocabID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabWordTypes", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Vocabularies", "Vocabulary")
                        .WithMany("VocabWordTypes")
                        .HasForeignKey("VocabID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.WordTypes", "WordType")
                        .WithMany("VocabWordTypes")
                        .HasForeignKey("WordTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");

                    b.Navigation("WordType");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Vocabularies", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.JLPT_Level", "JLPTLevel")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JLPTLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.VocabularyKanjis", b =>
                {
                    b.HasOne("QuizzTiengNhat.Models.Kanjis", "Kanji")
                        .WithMany("RelatedVocabularies")
                        .HasForeignKey("KanjiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizzTiengNhat.Models.Vocabularies", "Vocabulary")
                        .WithMany("RelatedKanjis")
                        .HasForeignKey("VocabID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kanji");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("ExamTemplate", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Exams", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ApplicationUser", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Courses", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.GrammarGroups", b =>
                {
                    b.Navigation("Grammars");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Grammars", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("GrammarTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.JLPT_Level", b =>
                {
                    b.Navigation("ExamTemplates");

                    b.Navigation("Grammars");

                    b.Navigation("Kanjis");

                    b.Navigation("Lessons");

                    b.Navigation("Questions");

                    b.Navigation("Users");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Kanjis", b =>
                {
                    b.Navigation("RelatedVocabularies");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Lessons", b =>
                {
                    b.Navigation("LessonTopics");

                    b.Navigation("Progresses");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Listenings", b =>
                {
                    b.Navigation("ListeningTopics");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Questions", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ExamQuestions");

                    b.Navigation("QuestionTopics");

                    b.Navigation("SubQuestions");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Radicals", b =>
                {
                    b.Navigation("Kanjis");

                    b.Navigation("RadicalVariants");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Readings", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("ReadingTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Topics", b =>
                {
                    b.Navigation("GrammarTopics");

                    b.Navigation("LessonTopics");

                    b.Navigation("ListeningTopics");

                    b.Navigation("QuestionTopics");

                    b.Navigation("ReadingTopics");

                    b.Navigation("VocabTopics");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.Vocabularies", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("RelatedKanjis");

                    b.Navigation("VocabTopics");

                    b.Navigation("VocabWordTypes");
                });

            modelBuilder.Entity("QuizzTiengNhat.Models.WordTypes", b =>
                {
                    b.Navigation("VocabWordTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
